theme: jekyll-theme-leap-day
markdown: kramdown
include: ./gsoc2019/gsoc2019.md


title: "Panagiotis Repouskos"
description: "My corner on the Web"
show_downloads: true

github:
  gsoc2019:  "gsoc2019/gsoc2019"


kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3
